# -*- coding: utf-8 -*-
"""3B-CABREZA-EXER3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MfyVHN-fGhLeKsAqtxc14-ZvDUG7I9KJ

#Part: 1 Defining the Problem and System Design

Disease: Heart Disease

Contributing Factors: High Blood Pressure, High Cholesterol, Physical Inactivity, Unhealthy Diet,Excessive Alcohol Consumption

#Part 2: Basic Probability Calculations
"""

P_Disease = 0.02
P_Positive_Disease = 0.95
P_Postive_No_Disease = 0.05
P_Positive = 0.06

Result = P_Positive_Disease * P_Disease / P_Positive

print(f"Posterior Probability: {Result}")

"""#Part 3: Decision-Making Simulation"""

P_Success = 0.7
Benefit = 100
P_Failure = 0.3
Loss = 50

Result = P_Success * Benefit + P_Failure * Loss

print(f"Expected Improvement: {Result}")

"""#Part 4: Visualize a Probability Distribution"""

import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import binom

n = 5
p = 0.5

k_values = np.arange(0, n + 1)

probabilities = binom.pmf(k_values, n, p)

plt.bar(k_values, probabilities, color='crimson')
plt.xlabel('Number of Heads')
plt.ylabel('Probability')
plt.title('Probability Distribution of Getting Heads in 5 Coin Flips')
plt.show()

"""#Reflection

Understanding probability theory helps us, in making better decisions in medical diagnosis. It help us
in making decisions easy and more accurate based on the given data, making the quality of healthcare better and safer. It can also help us determine what is the best course of action to do, based on the probability of the disease presented.
"""